
mcux_add_macro(
    CC "-DBOARD_DEBUG_UART_CLK_ROOT=kCLOCK_Root_Lpuart0304\
       -DBOARD_DEBUG_UART_BASEADDR=LPUART3\
       -DBOARD_DEBUG_UART_INSTANCE=3\
       -DBOARD_UART_IRQ=LPUART3_IRQn\
       -DBOARD_UART_IRQ_HANDLER=LPUART3_IRQHandler\
       -DMCMGR_HANDLE_EXCEPTIONS=1\
       -D__SEMIHOST_HARDFAULT_DISABLE=1"
)
